// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetApiV1AdminProductsCategoriesData,
  GetApiV1AdminProductsCategoriesErrors,
  GetApiV1AdminProductsCategoriesResponses,
  GetApiV1AdminProductsData,
  GetApiV1AdminProductsErrors,
  GetApiV1AdminProductsResponses,
  GetApiV1HealthData,
  GetApiV1HealthResponses,
  GetApiV1ProductCategoriesData,
  GetApiV1ProductCategoriesErrors,
  GetApiV1ProductCategoriesResponses,
  GetApiV1ProductCollabData,
  GetApiV1ProductCollabErrors,
  GetApiV1ProductCollabResponses,
  GetApiV1ProductIdData,
  GetApiV1ProductIdErrors,
  GetApiV1ProductIdResponses,
  GetApiV1ProductMerchData,
  GetApiV1ProductMerchErrors,
  GetApiV1ProductMerchResponses,
  GetApiV1ProductPanitiaData,
  GetApiV1ProductPanitiaErrors,
  GetApiV1ProductPanitiaResponses,
  GetApiV1UserProfileData,
  GetApiV1UserProfileErrors,
  GetApiV1UserProfileIsAdminData,
  GetApiV1UserProfileIsAdminErrors,
  GetApiV1UserProfileIsAdminResponses,
  GetApiV1UserProfileResponses,
  PatchApiV1UserProfileData,
  PatchApiV1UserProfileErrors,
  PatchApiV1UserProfileResponses,
  PostApiV1AuthChangePasswordData,
  PostApiV1AuthChangePasswordErrors,
  PostApiV1AuthChangePasswordResponses,
  PostApiV1AuthLoginData,
  PostApiV1AuthLoginErrors,
  PostApiV1AuthLoginResponses,
  PostApiV1AuthLogoutData,
  PostApiV1AuthLogoutErrors,
  PostApiV1AuthLogoutResponses,
  PostApiV1AuthOnboardingData,
  PostApiV1AuthOnboardingErrors,
  PostApiV1AuthOnboardingResponses,
  PostApiV1AuthRefreshTokenData,
  PostApiV1AuthRefreshTokenErrors,
  PostApiV1AuthRefreshTokenResponses,
  PostApiV1AuthResendOtpData,
  PostApiV1AuthResendOtpErrors,
  PostApiV1AuthResendOtpResponses,
  PostApiV1AuthSignupData,
  PostApiV1AuthSignupErrors,
  PostApiV1AuthSignupResponses,
  PostApiV1AuthVerifyOtpData,
  PostApiV1AuthVerifyOtpErrors,
  PostApiV1AuthVerifyOtpResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Registrasi pengguna baru
 *
 * Mendaftarkan akun baru dengan nama, email, dan password. Setelah berhasil, OTP 6 digit dikirim ke email yang didaftarkan. OTP berlaku 10 menit. Rate limit: 3 request per jam per IP.
 */
export const postApiV1AuthSignup = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1AuthSignupData, ThrowOnError>,
): RequestResult<PostApiV1AuthSignupResponses, PostApiV1AuthSignupErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiV1AuthSignupResponses,
    PostApiV1AuthSignupErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/signup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Login pengguna
 *
 * Autentikasi dengan email dan password. Mengembalikan access token (15 menit) di body dan refresh token (7 hari) via HTTP-only cookie (`refresh_token`). Pesan error sengaja dibuat generik untuk mencegah user enumeration. Rate limit: 5 percobaan per 15 menit per IP/akun.
 */
export const postApiV1AuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1AuthLoginData, ThrowOnError>,
): RequestResult<PostApiV1AuthLoginResponses, PostApiV1AuthLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiV1AuthLoginResponses,
    PostApiV1AuthLoginErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Verifikasi OTP email
 *
 * Memverifikasi kode OTP 6 digit yang dikirim ke email saat signup. OTP berlaku 10 menit. Setelah berhasil, mengembalikan `onboardingToken` yang digunakan sebagai Bearer token di endpoint POST /auth/onboarding.
 */
export const postApiV1AuthVerifyOtp = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1AuthVerifyOtpData, ThrowOnError>,
): RequestResult<PostApiV1AuthVerifyOtpResponses, PostApiV1AuthVerifyOtpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiV1AuthVerifyOtpResponses,
    PostApiV1AuthVerifyOtpErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/verify-otp',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Kirim ulang OTP
 *
 * Mengirimkan ulang kode OTP ke email yang belum terverifikasi. OTP baru akan menonaktifkan OTP lama. Rate limit: 3 request per jam per IP.
 */
export const postApiV1AuthResendOtp = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1AuthResendOtpData, ThrowOnError>,
): RequestResult<PostApiV1AuthResendOtpResponses, PostApiV1AuthResendOtpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiV1AuthResendOtpResponses,
    PostApiV1AuthResendOtpErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/resend-otp',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Perbarui access token
 *
 * Menggunakan refresh token dari HTTP-only cookie `refresh_token` untuk mendapatkan access token baru. Refresh token di-rotate: cookie baru dengan token baru diset, token lama dinonaktifkan.
 */
export const postApiV1AuthRefreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1AuthRefreshTokenData, ThrowOnError>,
): RequestResult<
  PostApiV1AuthRefreshTokenResponses,
  PostApiV1AuthRefreshTokenErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PostApiV1AuthRefreshTokenResponses,
    PostApiV1AuthRefreshTokenErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'refresh_token',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth/refresh-token',
    ...options,
  });

/**
 * Logout pengguna
 *
 * Menginvalidasi refresh token di server dan menghapus cookie `refresh_token`. Access token tetap berlaku hingga kedaluwarsa (15 menit). Untuk keamanan tinggi (mis. setelah change password), gunakan endpoint change-password yang menginvalidasi semua sesi.
 */
export const postApiV1AuthLogout = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1AuthLogoutData, ThrowOnError>,
): RequestResult<PostApiV1AuthLogoutResponses, PostApiV1AuthLogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    PostApiV1AuthLogoutResponses,
    PostApiV1AuthLogoutErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/auth/logout',
    ...options,
  });

/**
 * Ganti password
 *
 * Memperbarui password pengguna yang sedang login. Memerlukan verifikasi password lama. Password baru harus memenuhi kriteria kekuatan (min 8 karakter, huruf besar, huruf kecil, angka). Setelah berhasil, seluruh refresh token aktif pengguna dinonaktifkan (force logout semua device).
 */
export const postApiV1AuthChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1AuthChangePasswordData, ThrowOnError>,
): RequestResult<
  PostApiV1AuthChangePasswordResponses,
  PostApiV1AuthChangePasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiV1AuthChangePasswordResponses,
    PostApiV1AuthChangePasswordErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/auth/change-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Selesaikan onboarding akun
 *
 * Melengkapi data profil setelah OTP terverifikasi. Memerlukan `onboardingToken` dari endpoint POST /auth/verify-otp sebagai Bearer token. Jika `role = panitia`, `nim` dan `divisionCode` wajib diisi dan divalidasi terhadap database. Setelah berhasil, mengembalikan access token permanen dan refresh token (cookie).
 */
export const postApiV1AuthOnboarding = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1AuthOnboardingData, ThrowOnError>,
): RequestResult<PostApiV1AuthOnboardingResponses, PostApiV1AuthOnboardingErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiV1AuthOnboardingResponses,
    PostApiV1AuthOnboardingErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'onboardingAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/auth/onboarding',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Ambil profil pengguna yang sedang login
 *
 * Mengembalikan data lengkap profil pengguna berdasarkan access token. Untuk panitia, menyertakan data divisi. Endpoint ini aman digunakan untuk pre-fill form checkout.
 */
export const getApiV1UserProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1UserProfileData, ThrowOnError>,
): RequestResult<GetApiV1UserProfileResponses, GetApiV1UserProfileErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiV1UserProfileResponses,
    GetApiV1UserProfileErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/user/profile',
    ...options,
  });

/**
 * Perbarui data profil pengguna
 *
 * Memperbarui field profil yang dikirim (partial update - hanya field yang disertakan yang diubah). Field yang dapat diubah: name, lineId, phone. Email, role, kelompok, NIM, dan divisi panitia tidak dapat diubah mandiri.
 */
export const patchApiV1UserProfile = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiV1UserProfileData, ThrowOnError>,
): RequestResult<PatchApiV1UserProfileResponses, PatchApiV1UserProfileErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    PatchApiV1UserProfileResponses,
    PatchApiV1UserProfileErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/user/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Cek apakah pengguna adalah admin
 *
 * Memeriksa apakah pengguna yang sedang login memiliki role admin. Berguna untuk kondisional rendering di frontend (menampilkan/menyembunyikan fitur admin).
 */
export const getApiV1UserProfileIsAdmin = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1UserProfileIsAdminData, ThrowOnError>,
): RequestResult<
  GetApiV1UserProfileIsAdminResponses,
  GetApiV1UserProfileIsAdminErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetApiV1UserProfileIsAdminResponses,
    GetApiV1UserProfileIsAdminErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/user/profile/is-admin',
    ...options,
  });

/**
 * Daftar produk merchandise
 *
 * Mengambil daftar produk bertipe `merchandise`. Dapat diakses oleh semua pengguna (umum, panitia, admin). Mendukung paginasi, pencarian teks, dan filter kategori.
 */
export const getApiV1ProductMerch = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1ProductMerchData, ThrowOnError>,
): RequestResult<GetApiV1ProductMerchResponses, GetApiV1ProductMerchErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiV1ProductMerchResponses,
    GetApiV1ProductMerchErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/product/merch',
    ...options,
  });

/**
 * Daftar produk kit panitia
 *
 * Mengambil daftar produk bertipe `kit_panitia`. **Hanya dapat diakses oleh pengguna dengan role `panitia` atau `admin`.** Pengguna dengan role `umum` akan mendapat error 403.
 */
export const getApiV1ProductPanitia = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1ProductPanitiaData, ThrowOnError>,
): RequestResult<GetApiV1ProductPanitiaResponses, GetApiV1ProductPanitiaErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiV1ProductPanitiaResponses,
    GetApiV1ProductPanitiaErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/product/panitia',
    ...options,
  });

/**
 * Daftar produk kolaborasi
 *
 * Mengambil daftar produk bertipe `collaboration`. Dapat diakses oleh umum, panitia, dan admin. Mendukung filter `faculty` untuk menyaring produk kolaborasi per fakultas.
 */
export const getApiV1ProductCollab = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1ProductCollabData, ThrowOnError>,
): RequestResult<GetApiV1ProductCollabResponses, GetApiV1ProductCollabErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiV1ProductCollabResponses,
    GetApiV1ProductCollabErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/product/collab',
    ...options,
  });

/**
 * Produk berdasarkan kategori
 *
 * Mengambil produk yang difilter berdasarkan kategori. Jika query `category` tidak disertakan, mengembalikan semua produk yang dapat diakses oleh role pengguna tersebut. Produk `kit_panitia` hanya dikembalikan untuk panitia/admin.
 */
export const getApiV1ProductCategories = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1ProductCategoriesData, ThrowOnError>,
): RequestResult<
  GetApiV1ProductCategoriesResponses,
  GetApiV1ProductCategoriesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetApiV1ProductCategoriesResponses,
    GetApiV1ProductCategoriesErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/product/categories',
    ...options,
  });

/**
 * Detail produk berdasarkan ID
 *
 * Mengambil detail lengkap satu produk beserta semua gambar dan seluruh varian (sleeve type, warna, ukuran, harga final). Produk `kit_panitia` hanya dapat diakses oleh panitia/admin — pengguna umum mendapat error 403.
 */
export const getApiV1ProductId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1ProductIdData, ThrowOnError>,
): RequestResult<GetApiV1ProductIdResponses, GetApiV1ProductIdErrors, ThrowOnError> =>
  (options.client ?? client).get<GetApiV1ProductIdResponses, GetApiV1ProductIdErrors, ThrowOnError>(
    {
      security: [
        {
          key: 'bearerAuth',
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/api/v1/product/:id',
      ...options,
    },
  );

/**
 * [Admin] Semua produk dengan statistik penjualan
 *
 * Mengambil daftar seluruh produk (termasuk `kit_panitia` dan produk nonaktif) beserta statistik penjualan per produk dan per varian. **Hanya dapat diakses oleh admin.** Data penjualan dihitung dari order dengan status `lunas` dan `diterima`. Mendukung filter tipe, kategori, pencarian teks, dan pengurutan berdasarkan metrik penjualan.
 */
export const getApiV1AdminProducts = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1AdminProductsData, ThrowOnError>,
): RequestResult<GetApiV1AdminProductsResponses, GetApiV1AdminProductsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiV1AdminProductsResponses,
    GetApiV1AdminProductsErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/products',
    ...options,
  });

/**
 * [Admin] Produk per kategori dengan statistik penjualan
 *
 * Mengambil produk yang difilter berdasarkan kategori, disertai statistik penjualan. Jika query `category` tidak disertakan, mengembalikan semua produk dari semua kategori. **Hanya dapat diakses oleh admin.** Berguna untuk analisis performa kategori produk di dashboard.
 */
export const getApiV1AdminProductsCategories = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1AdminProductsCategoriesData, ThrowOnError>,
): RequestResult<
  GetApiV1AdminProductsCategoriesResponses,
  GetApiV1AdminProductsCategoriesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetApiV1AdminProductsCategoriesResponses,
    GetApiV1AdminProductsCategoriesErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/products/categories',
    ...options,
  });

/**
 * Server health check
 */
export const getApiV1Health = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1HealthData, ThrowOnError>,
): RequestResult<GetApiV1HealthResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiV1HealthResponses, unknown, ThrowOnError>({
    url: '/api/v1/health',
    ...options,
  });
