// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://backend-ecommerce-production-7c80.up.railway.app' | (string & {});
};

export type SignupResponse = {
    success: true;
    data: {
        message: string;
        email: string;
    };
};

export type ErrorResponse = {
    success: false;
    error: {
        code: string;
        message: string;
    };
};

export type SignupBody = {
    name: string;
    email: string;
    /**
     * Min 8 karakter, mengandung huruf besar, huruf kecil, dan angka
     */
    password: string;
};

export type LoginResponse = {
    success: true;
    data:
        | {
            onboardingRequired: false;
            accessToken: string;
            user: AuthUser;
        }
        | {
            onboardingRequired: true;
            onboardingToken: string;
            user: AuthUser;
        };
};

export type AuthUser = {
    id: string;
    name: string;
    email: string;
    role: 'umum' | 'panitia' | 'admin';
    isOnboardingComplete: boolean;
};

export type LoginBody = {
    email: string;
    password: string;
};

export type VerifyOtpResponse = {
    success: true;
    data: {
        /**
         * Token sementara untuk proses onboarding. Gunakan sebagai Bearer token di endpoint POST /auth/onboarding. Berlaku 30 menit.
         */
        onboardingToken: string;
        message: string;
    };
};

export type VerifyOtpBody = {
    email: string;
    otp: string;
};

export type ResendOtpResponse = {
    success: true;
    data: {
        message: string;
    };
};

export type ResendOtpBody = {
    email: string;
};

export type RefreshTokenResponse = {
    success: true;
    data: {
        accessToken: string;
    };
};

export type LogoutResponse = {
    success: true;
    data: {
        message: string;
    };
};

export type ChangePasswordResponse = {
    success: true;
    data: {
        message: string;
    };
};

export type ChangePasswordBody = {
    oldPassword: string;
    /**
     * Min 8 karakter, mengandung huruf besar, huruf kecil, dan angka
     */
    newPassword: string;
    /**
     * Harus sama dengan newPassword
     */
    confirmPassword: string;
};

export type OnboardingResponse = {
    success: true;
    data: {
        accessToken: string;
        user: AuthUser;
    };
};

export type OnboardingBody = {
    /**
     * ID LINE akun pengguna
     */
    lineId: string;
    phone: string;
    /**
     * Tipe pengguna yang dipilih saat onboarding
     */
    role: 'umum' | 'panitia';
    /**
     * NIM mahasiswa. Wajib diisi jika role = panitia, opsional jika role = umum.
     */
    nim?: string;
    /**
     * Nomor kelompok MaBa. Opsional jika role = umum.
     */
    kelompok?: string;
    /**
     * Kode bidang panitia. Field legacy, tidak wajib karena data panitia disiapkan lewat seed.
     */
    divisionCode?: string;
};

export type UserProfileResponse = {
    success: true;
    data: UserProfile;
};

export type UserProfile = {
    id: string;
    name: string;
    email: string;
    role: 'umum' | 'panitia' | 'admin';
    lineId: string;
    phone: string;
    /**
     * Khusus panitia
     */
    nim: string;
    division: Division;
    /**
     * Nomor kelompok MaBa. Opsional untuk umum.
     */
    kelompok: string;
};

/**
 * Bidang panitia. Null jika bukan panitia.
 */
export type Division = {
    id: string;
    name: string;
    code: string;
};

export type PatchProfileResponse = {
    success: true;
    data: UserProfile;
};

export type PatchProfileBody = {
    name?: string;
    lineId?: string;
    phone?: string;
};

export type IsAdminResponse = {
    success: true;
    data: {
        isAdmin: boolean;
    };
};

export type ProductListResponse = {
    success: true;
    data: Array<ProductListItem>;
    meta: PaginationMeta;
};

export type ProductListItem = {
    id: string;
    name: string;
    description: string;
    basePrice: number;
    type: 'merchandise' | 'collaboration' | 'kit_panitia';
    category: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle';
    /**
     * Nama fakultas, hanya untuk produk collaboration
     */
    faculty: string;
    primaryImage: ProductImage;
    variantCount: number;
    minPrice: number;
    maxPrice: number;
};

/**
 * Gambar utama produk (is_primary = true)
 */
export type ProductImage = {
    id: string;
    url: string;
    isPrimary: boolean;
    sortOrder: number;
};

export type PaginationMeta = {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
};

export type BundleListResponse = {
    success: true;
    data: Array<BundleListItem>;
    meta: PaginationMeta;
};

export type BundleImage = {
    id: string;
    url: string;
    altText: string | null;
    /**
     * Kode divisi untuk artwork khusus divisi; null untuk gambar umum bundle.
     */
    variantKey: string | null;
    isPrimary: boolean;
    sortOrder: number;
};

export type BundleListItem = {
    id: string;
    name: string;
    description: string;
    price: number;
    type: 'merchandise_bundle' | 'kit_panitia_bundle' | 'kit_panitia_add_on' | 'kit_panitia_ala_carte';
    targetRoles: Array<'umum' | 'panitia' | 'admin'>;
    targetDivisions: Array<string> | null;
    /**
     * Gambar utama bundle, atau null jika gambar belum diunggah.
     */
    primaryImage: BundleImage | null;
    itemCount: number;
    isActive: boolean;
};

export type BundleDetailResponse = {
    success: true;
    data: BundleDetail;
};

export type BundleDetail = BundleListItem & {
    metadata: {
        [key: string]: unknown;
    };
    items: Array<{
        productId: string;
        productName: string;
        quantity: number;
        isOptional: boolean;
        optionGroup: string;
        variants: Array<ProductVariant>;
    }>;
    /**
     * Semua gambar bundle. Untuk panitia, pilih yang variantKey == kode divisi.
     */
    images: Array<BundleImage>;
    /**
     * Add-on panitia (hanya pada bundle kit_panitia_bundle).
     */
    addOns?: Array<BundleListItem>;
};

export type ProductVariantImage = {
    id: string;
    url: string;
    altText: string | null;
    /**
     * Peran asset, misalnya primary, design, mockup, gallery
     */
    role: string;
    isPrimary: boolean;
    sortOrder: number;
};

export type ProductVariant = {
    id: string;
    sleeveType: 'lengan_panjang' | 'lengan_pendek' | 'none';
    color: string;
    size: 'S' | 'M' | 'L' | 'XL' | 'XXL' | '3XL' | '4XL' | 'none';
    /**
     * Harga tambahan di atas base_price produk
     */
    priceModifier: number;
    stock: number;
    sku: string;
    /**
     * Harga akhir = base_price + price_modifier
     */
    finalPrice: number;
    /**
     * Gambar spesifik varian. Kosong jika varian memakai gambar produk utama.
     */
    images: Array<ProductVariantImage>;
};

export type ProductDetailResponse = {
    success: true;
    data: ProductDetail;
};

export type ProductDetail = {
    id: string;
    name: string;
    description: string;
    basePrice: number;
    type: 'merchandise' | 'collaboration' | 'kit_panitia';
    category: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle';
    faculty: string;
    /**
     * Semua gambar produk, diurutkan berdasarkan sort_order
     */
    images: Array<ProductImage>;
    /**
     * Semua varian produk yang tersedia
     */
    variants: Array<ProductVariant>;
    /**
     * Size chart produk jika tersedia
     */
    sizeChart: Array<{
        size: string;
        widthCm: number;
        lengthCm: number;
        toleranceCm: number;
    }>;
};

export type GetCartCountResponse = {
    success: true;
    data: {
        /**
         * Total quantity seluruh item cart user
         */
        count: number;
    };
};

export type GetCartResponse = {
    success: true;
    data: {
        items: Array<CartItem>;
        summary: CartSummary;
    };
};

export type CartItem = {
    id: string;
    quantity: number;
    /**
     * basePrice + priceModifier varian
     */
    unitPrice: number;
    /**
     * unitPrice x quantity
     */
    subtotal: number;
    itemType: 'variant' | 'bundle';
    variant: CartItemVariant;
    product: CartItemProduct;
    bundle: {
        id: string;
        name: string;
        description: string;
        type: 'merchandise_bundle' | 'kit_panitia_bundle' | 'kit_panitia_add_on' | 'kit_panitia_ala_carte';
        items: Array<{
            productId: string;
            productName: string;
            quantity: number;
            isOptional: boolean;
            optionGroup: string;
            selectedVariants: Array<{
                variantId: string;
                quantity: number;
                size: string;
                color: string;
                sleeveType: string;
                sku: string;
            }>;
        }>;
    };
    createdAt: string;
    updatedAt: string;
};

export type CartItemVariant = {
    id: string;
    sleeveType: 'lengan_panjang' | 'lengan_pendek' | 'none';
    color: string;
    size: 'S' | 'M' | 'L' | 'XL' | 'XXL' | '3XL' | '4XL' | 'none';
    priceModifier: number;
    stock: number;
    sku: string;
};

export type CartItemProduct = {
    id: string;
    name: string;
    description: string;
    basePrice: number;
    type: 'merchandise' | 'collaboration' | 'kit_panitia';
    category: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle';
    imageUrl: string;
};

export type CartSummary = {
    totalItems: number;
    totalQuantity: number;
    totalAmount: number;
};

export type AddToCartResponse = {
    success: true;
    data: {
        item: CartItem;
        summary: CartSummary;
    };
};

export type AddToCartBody = {
    /**
     * ID varian produk yang ingin ditambahkan ke cart
     */
    variantId?: string;
    /**
     * ID bundle yang ingin ditambahkan ke cart
     */
    bundleId?: string;
    /**
     * Pilihan varian komponen bundle. Wajib untuk bundle yang berisi produk dengan varian seperti kaos.
     */
    selectedVariants?: Array<{
        productId: string;
        variantId: string;
        quantity: number;
    }>;
    quantity: number;
};

export type UpdateCartItemResponse = {
    success: true;
    data: {
        item: CartItem;
        summary: CartSummary;
    };
};

export type UpdateCartItemBody = {
    /**
     * Quantity baru. Minimal 1. Gunakan DELETE untuk menghapus item.
     */
    quantity: number;
};

export type DeleteCartItemResponse = {
    success: true;
    data: {
        message: string;
        summary: CartSummary;
    };
};

export type InitiateOrderResponse = {
    success: true;
    data: OrderDraft;
};

export type OrderDraft = {
    order_id: string;
    status: 'draft';
    items: Array<OrderItemSnapshot>;
    summary: OrderSummary;
};

export type OrderItemSnapshot = {
    product_id: string;
    product_name: string;
    image_url: string;
    variant: {
        id: string;
        size: string;
        color: string;
        sleeve_type: string;
    };
    bundle?: {
        [key: string]: unknown;
    };
    unit_price: number;
    quantity: number;
    subtotal: number;
};

export type OrderSummary = {
    total_items: number;
    total_product_price: number;
};

export type InitiateOrderBody = {
    cart_item_ids: Array<string>;
};

export type OrderHistoryResponse = {
    success: true;
    data: Array<{
        id: string;
        status: 'draft' | 'belum_bayar' | 'lunas' | 'diterima' | 'expired';
        totalBilled: number;
        itemCount: number;
        createdAt: string;
        paidAt: string;
    }>;
};

export type CheckoutResponse = {
    success: true;
    data: CheckoutOrder;
};

export type CheckoutOrder = {
    order_id: string;
    status: 'draft';
    items: Array<OrderItemSnapshot>;
    user_prefill: {
        name: string;
        phone: string;
        line: string;
    };
    delivery_options: Array<OrderOption>;
    payment_methods: Array<OrderOption>;
    summary: OrderSummary;
};

export type OrderOption = {
    value: string;
    label: string;
};

export type ConfirmOrderResponse = {
    success: true;
    data: {
        order_id: string;
        status: 'belum_bayar';
        delivery_method: OrderDeliveryMethod;
        payment_method: OrderPaymentMethod;
        payment_expired_at: string;
        redirect_url: string;
    };
};

export type OrderDeliveryMethod = 'pickup' | 'shipping';

export type OrderPaymentMethod = 'qris' | 'bca_va';

export type ConfirmOrderBody = {
    order_id: string;
    delivery_method: OrderDeliveryMethod & unknown;
    receiver: OrderReceiver;
    payment_method: OrderPaymentMethod & unknown;
};

export type OrderReceiver = {
    name: string;
    phone: string;
    line: string;
    address: string;
};

export type OrderDetailResponse = {
    success: true;
    data: OrderDetail;
};

export type OrderDetail = {
    id: string;
    status: 'draft' | 'belum_bayar' | 'lunas' | 'diterima' | 'expired';
    deliveryMethod: OrderDeliveryMethod & unknown;
    deliveryAddress: string;
    contactName: string;
    contactPhone: string;
    contactLineId: string;
    paymentMethod: OrderPaymentMethod & unknown;
    totalAmount: number;
    gatewayFee: number;
    totalBilled: number;
    paymentExpiredAt: string;
    paidAt: string;
    createdAt: string;
    items: Array<{
        id: string;
        productName: string;
        productType: 'merchandise' | 'collaboration' | 'kit_panitia';
        productCategory: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle';
        variantSnapshot: {
            [key: string]: unknown;
        };
        bundleSnapshot?: {
            [key: string]: unknown;
        };
        unitPrice: number;
        quantity: number;
        subtotal: number;
    }>;
};

export type GenerateQrResponse = {
    success: true;
    data: {
        qrDataUrl: string;
        expiresAt: string;
    };
};

export type PaymentFeeResponse = {
    success: true;
    data: {
        method: string;
        subtotal: number;
        fee: number;
        total: number;
    };
};

export type PaymentWebhookResponse = {
    success: true;
};

export type PaymentWebhookBody = {
    order_id: string;
    status_code: string;
    gross_amount: string;
    signature_key: string;
    transaction_status: string;
    transaction_id?: string;
    payment_type?: string;
    fraud_status?: string;
    transaction_time?: string;
    status_message?: string;
    settlement_time?: string;
    merchant_id?: string;
    currency?: string;
    [key: string]: unknown;
};

export type PaymentMethodsResponse = {
    success: true;
    data: Array<PaymentMethod>;
};

export type PaymentMethod = {
    id: string;
    code: string;
    name: string;
    type: 'qris' | 'bank_transfer';
    feeType: 'fixed' | 'percentage';
    feeValue: number;
};

export type InitiatePaymentResponse = {
    success: true;
    data: {
        paymentId: string;
        paymentReference: string;
        method: string;
        expiredAt: string;
        qrString?: string;
        qrImageUrl?: string;
        bank?: string;
        accountNumber?: string;
        amount: number;
    };
};

export type InitiatePaymentBody = {
    method: string;
};

export type PaymentStatusResponse = {
    success: true;
    data: {
        status: 'belum_bayar' | 'lunas' | 'expired' | 'diterima';
    };
};

export type PaymentDetailResponse = {
    success: true;
    data: {
        status: 'belum_bayar' | 'lunas' | 'expired';
        method: string;
        expiredAt: string;
        /**
         * Sisa waktu pembayaran dalam detik (0 jika expired)
         */
        countdown: number;
        orderSummary: {
            orderId: string;
            subtotal: number;
            fee: number;
            total: number;
            items: Array<{
                productName: string;
                variant: {
                    [key: string]: unknown;
                };
                quantity: number;
                unitPrice: number;
                subtotal: number;
            }>;
        };
        shipping: {
            method: string;
            name: string;
            phone: string;
            address: string;
        };
        paymentDetail: {
            fee: number;
            qrString?: string;
            qrImageUrl?: string;
            bank?: string;
            accountNumber?: string;
        };
    };
};

export type AdminProductListResponse = {
    success: true;
    data: Array<AdminProduct>;
    meta: PaginationMeta;
};

export type AdminProduct = {
    id: string;
    name: string;
    description: string;
    basePrice: number;
    type: 'merchandise' | 'collaboration' | 'kit_panitia';
    category: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle';
    faculty: string;
    isActive: boolean;
    primaryImage: ProductImage;
    salesStats: ProductSalesStats;
};

export type ProductSalesStats = {
    /**
     * Total unit terjual dari semua varian produk ini
     */
    totalSold: number;
    /**
     * Total pendapatan produk ini dari semua transaksi lunas (IDR)
     */
    totalRevenue: number;
    /**
     * Rincian penjualan per varian
     */
    variantStats: Array<VariantSalesStats>;
};

export type VariantSalesStats = {
    variantId: string;
    sleeveType: 'lengan_panjang' | 'lengan_pendek' | 'none';
    color: string;
    size: 'S' | 'M' | 'L' | 'XL' | 'XXL' | '3XL' | '4XL' | 'none';
    sku: string;
    /**
     * Harga per unit saat terjual
     */
    unitPrice: number;
    /**
     * Total unit terjual dari varian ini
     */
    totalSold: number;
    /**
     * Total pendapatan dari varian ini (IDR)
     */
    totalRevenue: number;
};

export type AdminTransactionListResponse = {
    success: true;
    data: Array<AdminTransaction>;
    meta: PaginationMeta;
};

export type AdminTransaction = {
    orderId: string;
    buyerName: string;
    buyerEmail: string;
    buyerPhone: string;
    buyerLineId: string;
    items: Array<AdminTransactionItem>;
    totalBilled: number;
    status: 'belum_bayar' | 'lunas' | 'diterima' | 'expired';
    paidAt: string;
    createdAt: string;
};

export type AdminTransactionItem = {
    productName: string;
    quantity: number;
};

export type AdminHandOverScanResponse = {
    success: true;
    data: {
        transactionId: string;
        orderId: string;
        buyerName: string;
        buyerEmail: string;
        buyerPhone: string;
        buyerLineId: string;
        items: Array<AdminHandOverScanItem>;
        totalBilled: number;
        status: 'lunas';
        paidAt: string;
    };
};

export type AdminHandOverScanItem = {
    productName: string;
    variantSnapshot: {
        [key: string]: unknown;
    };
    quantity: number;
};

export type AdminHandOverScanBody = {
    /**
     * Raw payload hasil scan QR pickup. Bisa berupa token polos atau JSON payload QR dari backend.
     */
    qrToken: string;
};

export type AdminHandOverConfirmResponse = {
    success: true;
    data: {
        orderId: string;
        status: 'diterima';
        updatedAt: string;
    };
};

export type PostApiV1AuthSignupData = {
    body: SignupBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup';
};

export type PostApiV1AuthSignupErrors = {
    /**
     * Validasi gagal (password lemah, format email salah, dll.)
     */
    400: ErrorResponse;
    /**
     * Email sudah terdaftar
     */
    409: ErrorResponse;
    /**
     * Terlalu banyak permintaan - rate limit terlampaui (maks 3x/jam/IP)
     */
    429: ErrorResponse;
};

export type PostApiV1AuthSignupError = PostApiV1AuthSignupErrors[keyof PostApiV1AuthSignupErrors];

export type PostApiV1AuthSignupResponses = {
    /**
     * Registrasi berhasil, OTP dikirim ke email
     */
    201: SignupResponse;
};

export type PostApiV1AuthSignupResponse = PostApiV1AuthSignupResponses[keyof PostApiV1AuthSignupResponses];

export type PostApiV1AuthLoginData = {
    body: LoginBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
    /**
     * Validasi gagal (field kosong, format email salah)
     */
    400: ErrorResponse;
    /**
     * Email atau password salah
     */
    401: ErrorResponse;
    /**
     * Email sudah terverifikasi tetapi onboarding belum selesai
     */
    403: ErrorResponse;
    /**
     * Terlalu banyak percobaan login - rate limit terlampaui (maks 5x/15 menit)
     */
    429: ErrorResponse;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
    /**
     * Login berhasil. Refresh token diset sebagai HTTP-only cookie `refresh_token`.
     */
    200: LoginResponse;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type GetApiV1AuthGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google';
};

export type GetApiV1AuthGoogleErrors = {
    /**
     * Google OAuth belum dikonfigurasi
     */
    500: ErrorResponse;
};

export type GetApiV1AuthGoogleError = GetApiV1AuthGoogleErrors[keyof GetApiV1AuthGoogleErrors];

export type GetApiV1AuthGoogleCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google/callback';
};

export type GetApiV1AuthGoogleCallbackErrors = {
    /**
     * Callback tidak valid atau gagal diverifikasi
     */
    401: ErrorResponse;
    /**
     * Email Google terdaftar sebagai panitia/admin
     */
    403: ErrorResponse;
};

export type GetApiV1AuthGoogleCallbackError = GetApiV1AuthGoogleCallbackErrors[keyof GetApiV1AuthGoogleCallbackErrors];

export type PostApiV1AuthVerifyOtpData = {
    body: VerifyOtpBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify-otp';
};

export type PostApiV1AuthVerifyOtpErrors = {
    /**
     * Validasi gagal, OTP salah/kedaluwarsa, atau email tidak menunggu verifikasi
     */
    400: ErrorResponse;
    /**
     * Terlalu banyak percobaan verifikasi OTP (maks 5x/10 menit/IP)
     */
    429: ErrorResponse;
};

export type PostApiV1AuthVerifyOtpError = PostApiV1AuthVerifyOtpErrors[keyof PostApiV1AuthVerifyOtpErrors];

export type PostApiV1AuthVerifyOtpResponses = {
    /**
     * OTP valid, onboardingToken dikembalikan
     */
    200: VerifyOtpResponse;
};

export type PostApiV1AuthVerifyOtpResponse = PostApiV1AuthVerifyOtpResponses[keyof PostApiV1AuthVerifyOtpResponses];

export type PostApiV1AuthResendOtpData = {
    body: ResendOtpBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/resend-otp';
};

export type PostApiV1AuthResendOtpErrors = {
    /**
     * Validasi gagal, email tidak ditemukan, atau akun sudah terverifikasi
     */
    400: ErrorResponse;
    /**
     * Terlalu banyak permintaan - rate limit terlampaui (maks 3x/jam/IP)
     */
    429: ErrorResponse;
};

export type PostApiV1AuthResendOtpError = PostApiV1AuthResendOtpErrors[keyof PostApiV1AuthResendOtpErrors];

export type PostApiV1AuthResendOtpResponses = {
    /**
     * OTP baru berhasil dikirim
     */
    200: ResendOtpResponse;
};

export type PostApiV1AuthResendOtpResponse = PostApiV1AuthResendOtpResponses[keyof PostApiV1AuthResendOtpResponses];

export type PostApiV1AuthRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh-token';
};

export type PostApiV1AuthRefreshTokenErrors = {
    /**
     * Refresh token tidak valid, kedaluwarsa, atau tidak ada cookie
     */
    401: ErrorResponse;
};

export type PostApiV1AuthRefreshTokenError = PostApiV1AuthRefreshTokenErrors[keyof PostApiV1AuthRefreshTokenErrors];

export type PostApiV1AuthRefreshTokenResponses = {
    /**
     * Access token baru berhasil dibuat. Refresh token baru diset sebagai HTTP-only cookie.
     */
    200: RefreshTokenResponse;
};

export type PostApiV1AuthRefreshTokenResponse = PostApiV1AuthRefreshTokenResponses[keyof PostApiV1AuthRefreshTokenResponses];

export type PostApiV1AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
    /**
     * Bearer access token tidak ada atau tidak valid
     */
    401: ErrorResponse;
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
    /**
     * Logout berhasil, cookie refresh_token dihapus
     */
    200: LogoutResponse;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type PostApiV1AuthChangePasswordData = {
    body: ChangePasswordBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password';
};

export type PostApiV1AuthChangePasswordErrors = {
    /**
     * Validasi gagal, konfirmasi tidak cocok, atau password baru sama dengan password lama
     */
    400: ErrorResponse;
    /**
     * Bearer access token tidak valid atau password lama salah
     */
    401: ErrorResponse;
};

export type PostApiV1AuthChangePasswordError = PostApiV1AuthChangePasswordErrors[keyof PostApiV1AuthChangePasswordErrors];

export type PostApiV1AuthChangePasswordResponses = {
    /**
     * Password berhasil diubah, semua sesi lain dinonaktifkan
     */
    200: ChangePasswordResponse;
};

export type PostApiV1AuthChangePasswordResponse = PostApiV1AuthChangePasswordResponses[keyof PostApiV1AuthChangePasswordResponses];

export type PostApiV1AuthOnboardingData = {
    body: OnboardingBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/onboarding';
};

export type PostApiV1AuthOnboardingErrors = {
    /**
     * Validasi gagal
     */
    400: ErrorResponse;
    /**
     * Onboarding token tidak valid atau kedaluwarsa
     */
    401: ErrorResponse;
    /**
     * Email belum diverifikasi atau akun bukan panitia seeded
     */
    403: ErrorResponse;
    /**
     * Onboarding sudah diselesaikan sebelumnya
     */
    409: ErrorResponse;
};

export type PostApiV1AuthOnboardingError = PostApiV1AuthOnboardingErrors[keyof PostApiV1AuthOnboardingErrors];

export type PostApiV1AuthOnboardingResponses = {
    /**
     * Onboarding berhasil. Access token dikembalikan, refresh token diset sebagai cookie.
     */
    200: OnboardingResponse;
};

export type PostApiV1AuthOnboardingResponse = PostApiV1AuthOnboardingResponses[keyof PostApiV1AuthOnboardingResponses];

export type GetApiV1UserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/profile';
};

export type GetApiV1UserProfileErrors = {
    /**
     * Tidak terautentikasi - access token tidak ada atau kedaluwarsa
     */
    401: ErrorResponse;
};

export type GetApiV1UserProfileError = GetApiV1UserProfileErrors[keyof GetApiV1UserProfileErrors];

export type GetApiV1UserProfileResponses = {
    /**
     * Data profil berhasil diambil
     */
    200: UserProfileResponse;
};

export type GetApiV1UserProfileResponse = GetApiV1UserProfileResponses[keyof GetApiV1UserProfileResponses];

export type PatchApiV1UserProfileData = {
    body: PatchProfileBody;
    path?: never;
    query?: never;
    url: '/api/v1/user/profile';
};

export type PatchApiV1UserProfileErrors = {
    /**
     * Validasi gagal (format nomor telepon salah, dll.)
     */
    400: ErrorResponse;
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
};

export type PatchApiV1UserProfileError = PatchApiV1UserProfileErrors[keyof PatchApiV1UserProfileErrors];

export type PatchApiV1UserProfileResponses = {
    /**
     * Profil berhasil diperbarui, mengembalikan data profil terbaru
     */
    200: PatchProfileResponse;
};

export type PatchApiV1UserProfileResponse = PatchApiV1UserProfileResponses[keyof PatchApiV1UserProfileResponses];

export type GetApiV1UserProfileIsAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/profile/is-admin';
};

export type GetApiV1UserProfileIsAdminErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
};

export type GetApiV1UserProfileIsAdminError = GetApiV1UserProfileIsAdminErrors[keyof GetApiV1UserProfileIsAdminErrors];

export type GetApiV1UserProfileIsAdminResponses = {
    /**
     * Status admin berhasil diperiksa
     */
    200: IsAdminResponse;
};

export type GetApiV1UserProfileIsAdminResponse = GetApiV1UserProfileIsAdminResponses[keyof GetApiV1UserProfileIsAdminResponses];

export type GetApiV1ProductData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Nomor halaman
         */
        page?: number;
        /**
         * Jumlah item per halaman
         */
        limit?: number;
        /**
         * Pencarian teks pada nama produk (case-insensitive)
         */
        search?: string;
        /**
         * Filter berdasarkan kategori. Bisa dikirim lebih dari satu.
         */
        category?: Array<'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle'>;
        /**
         * Filter berdasarkan tipe produk. Bisa dikirim lebih dari satu.
         */
        type?: Array<'merchandise' | 'collaboration' | 'kit_panitia'>;
        /**
         * Filter berdasarkan fakultas. Bisa dikirim lebih dari satu.
         */
        faculty?: Array<string>;
    };
    url: '/api/v1/product';
};

export type GetApiV1ProductResponses = {
    /**
     * Produk berhasil diambil
     */
    200: ProductListResponse;
};

export type GetApiV1ProductResponse = GetApiV1ProductResponses[keyof GetApiV1ProductResponses];

export type GetApiV1ProductBundlesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        type?: Array<'merchandise_bundle' | 'kit_panitia_bundle' | 'kit_panitia_add_on' | 'kit_panitia_ala_carte'>;
        search?: string;
    };
    url: '/api/v1/product/bundles';
};

export type GetApiV1ProductBundlesResponses = {
    /**
     * Bundle berhasil diambil
     */
    200: BundleListResponse;
};

export type GetApiV1ProductBundlesResponse = GetApiV1ProductBundlesResponses[keyof GetApiV1ProductBundlesResponses];

export type GetApiV1ProductBundlesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/product/bundles/{id}';
};

export type GetApiV1ProductBundlesByIdErrors = {
    /**
     * Bundle tidak ditemukan
     */
    404: ErrorResponse;
};

export type GetApiV1ProductBundlesByIdError = GetApiV1ProductBundlesByIdErrors[keyof GetApiV1ProductBundlesByIdErrors];

export type GetApiV1ProductBundlesByIdResponses = {
    /**
     * Detail bundle berhasil diambil
     */
    200: BundleDetailResponse;
};

export type GetApiV1ProductBundlesByIdResponse = GetApiV1ProductBundlesByIdResponses[keyof GetApiV1ProductBundlesByIdResponses];

export type GetApiV1ProductByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/product/{id}';
};

export type GetApiV1ProductByIdErrors = {
    /**
     * Produk tidak ditemukan
     */
    404: ErrorResponse;
};

export type GetApiV1ProductByIdError = GetApiV1ProductByIdErrors[keyof GetApiV1ProductByIdErrors];

export type GetApiV1ProductByIdResponses = {
    /**
     * Detail produk berhasil diambil
     */
    200: ProductDetailResponse;
};

export type GetApiV1ProductByIdResponse = GetApiV1ProductByIdResponses[keyof GetApiV1ProductByIdResponses];

export type GetApiV1CartCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cart/count';
};

export type GetApiV1CartCountErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
};

export type GetApiV1CartCountError = GetApiV1CartCountErrors[keyof GetApiV1CartCountErrors];

export type GetApiV1CartCountResponses = {
    /**
     * Total quantity cart berhasil diambil
     */
    200: GetCartCountResponse;
};

export type GetApiV1CartCountResponse = GetApiV1CartCountResponses[keyof GetApiV1CartCountResponses];

export type GetApiV1CartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cart';
};

export type GetApiV1CartErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
};

export type GetApiV1CartError = GetApiV1CartErrors[keyof GetApiV1CartErrors];

export type GetApiV1CartResponses = {
    /**
     * Isi cart berhasil diambil
     */
    200: GetCartResponse;
};

export type GetApiV1CartResponse = GetApiV1CartResponses[keyof GetApiV1CartResponses];

export type PostApiV1CartData = {
    body: AddToCartBody;
    path?: never;
    query?: never;
    url: '/api/v1/cart';
};

export type PostApiV1CartErrors = {
    /**
     * Validasi gagal (quantity kurang dari 1, variantId bukan UUID, dll.)
     */
    400: ErrorResponse;
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * User umum mencoba menambahkan produk kit panitia
     */
    403: ErrorResponse;
    /**
     * Produk atau varian tidak ditemukan
     */
    404: ErrorResponse;
};

export type PostApiV1CartError = PostApiV1CartErrors[keyof PostApiV1CartErrors];

export type PostApiV1CartResponses = {
    /**
     * Item berhasil ditambahkan ke cart
     */
    201: AddToCartResponse;
};

export type PostApiV1CartResponse = PostApiV1CartResponses[keyof PostApiV1CartResponses];

export type DeleteApiV1CartByItemIdData = {
    body?: never;
    path: {
        /**
         * ID cart item yang ingin dihapus
         */
        itemId: string;
    };
    query?: never;
    url: '/api/v1/cart/{itemId}';
};

export type DeleteApiV1CartByItemIdErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Item bukan milik user yang sedang login
     */
    403: ErrorResponse;
    /**
     * Item cart tidak ditemukan
     */
    404: ErrorResponse;
};

export type DeleteApiV1CartByItemIdError = DeleteApiV1CartByItemIdErrors[keyof DeleteApiV1CartByItemIdErrors];

export type DeleteApiV1CartByItemIdResponses = {
    /**
     * Item berhasil dihapus, summary cart terbaru dikembalikan
     */
    200: DeleteCartItemResponse;
};

export type DeleteApiV1CartByItemIdResponse = DeleteApiV1CartByItemIdResponses[keyof DeleteApiV1CartByItemIdResponses];

export type PatchApiV1CartByItemIdData = {
    body: UpdateCartItemBody;
    path: {
        /**
         * ID cart item yang ingin diupdate
         */
        itemId: string;
    };
    query?: never;
    url: '/api/v1/cart/{itemId}';
};

export type PatchApiV1CartByItemIdErrors = {
    /**
     * Validasi gagal (quantity kurang dari 1, itemId bukan UUID)
     */
    400: ErrorResponse;
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Item bukan milik user yang sedang login
     */
    403: ErrorResponse;
    /**
     * Item cart tidak ditemukan
     */
    404: ErrorResponse;
};

export type PatchApiV1CartByItemIdError = PatchApiV1CartByItemIdErrors[keyof PatchApiV1CartByItemIdErrors];

export type PatchApiV1CartByItemIdResponses = {
    /**
     * Quantity item berhasil diupdate
     */
    200: UpdateCartItemResponse;
};

export type PatchApiV1CartByItemIdResponse = PatchApiV1CartByItemIdResponses[keyof PatchApiV1CartByItemIdResponses];

export type PostApiV1OrderInitiateData = {
    body: InitiateOrderBody;
    path?: never;
    query?: never;
    url: '/api/v1/order/initiate';
};

export type PostApiV1OrderInitiateErrors = {
    /**
     * Input tidak valid
     */
    400: ErrorResponse;
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Item cart tidak valid atau bukan milik user
     */
    403: ErrorResponse;
};

export type PostApiV1OrderInitiateError = PostApiV1OrderInitiateErrors[keyof PostApiV1OrderInitiateErrors];

export type PostApiV1OrderInitiateResponses = {
    /**
     * Draft checkout berhasil dibuat
     */
    201: InitiateOrderResponse;
};

export type PostApiV1OrderInitiateResponse = PostApiV1OrderInitiateResponses[keyof PostApiV1OrderInitiateResponses];

export type GetApiV1OrderHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/order/history';
};

export type GetApiV1OrderHistoryErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
};

export type GetApiV1OrderHistoryError = GetApiV1OrderHistoryErrors[keyof GetApiV1OrderHistoryErrors];

export type GetApiV1OrderHistoryResponses = {
    /**
     * Riwayat order berhasil diambil
     */
    200: OrderHistoryResponse;
};

export type GetApiV1OrderHistoryResponse = GetApiV1OrderHistoryResponses[keyof GetApiV1OrderHistoryResponses];

export type GetApiV1OrderByOrderIdCheckoutData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/order/{orderId}/checkout';
};

export type GetApiV1OrderByOrderIdCheckoutErrors = {
    /**
     * Checkout sudah dikonfirmasi
     */
    400: ErrorResponse;
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Checkout tidak ditemukan
     */
    404: ErrorResponse;
};

export type GetApiV1OrderByOrderIdCheckoutError = GetApiV1OrderByOrderIdCheckoutErrors[keyof GetApiV1OrderByOrderIdCheckoutErrors];

export type GetApiV1OrderByOrderIdCheckoutResponses = {
    /**
     * Draft checkout berhasil diambil
     */
    200: CheckoutResponse;
};

export type GetApiV1OrderByOrderIdCheckoutResponse = GetApiV1OrderByOrderIdCheckoutResponses[keyof GetApiV1OrderByOrderIdCheckoutResponses];

export type PostApiV1OrderConfirmData = {
    body: ConfirmOrderBody;
    path?: never;
    query?: never;
    url: '/api/v1/order/confirm';
};

export type PostApiV1OrderConfirmErrors = {
    /**
     * Checkout tidak valid atau sudah dikonfirmasi
     */
    400: ErrorResponse;
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Checkout tidak ditemukan
     */
    404: ErrorResponse;
};

export type PostApiV1OrderConfirmError = PostApiV1OrderConfirmErrors[keyof PostApiV1OrderConfirmErrors];

export type PostApiV1OrderConfirmResponses = {
    /**
     * Checkout berhasil dikonfirmasi
     */
    200: ConfirmOrderResponse;
};

export type PostApiV1OrderConfirmResponse = PostApiV1OrderConfirmResponses[keyof PostApiV1OrderConfirmResponses];

export type GetApiV1OrderByOrderIdData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/order/{orderId}';
};

export type GetApiV1OrderByOrderIdErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Order ini bukan milik pengguna yang sedang login
     */
    403: ErrorResponse;
    /**
     * Order tidak ditemukan
     */
    404: ErrorResponse;
};

export type GetApiV1OrderByOrderIdError = GetApiV1OrderByOrderIdErrors[keyof GetApiV1OrderByOrderIdErrors];

export type GetApiV1OrderByOrderIdResponses = {
    /**
     * Detail order berhasil diambil
     */
    200: OrderDetailResponse;
};

export type GetApiV1OrderByOrderIdResponse = GetApiV1OrderByOrderIdResponses[keyof GetApiV1OrderByOrderIdResponses];

export type PostApiV1OrderByOrderIdGenerateQrData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/order/{orderId}/generate-qr';
};

export type PostApiV1OrderByOrderIdGenerateQrErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Order bukan milik pengguna ini, atau order belum berstatus lunas
     */
    403: ErrorResponse;
    /**
     * Order tidak ditemukan
     */
    404: ErrorResponse;
};

export type PostApiV1OrderByOrderIdGenerateQrError = PostApiV1OrderByOrderIdGenerateQrErrors[keyof PostApiV1OrderByOrderIdGenerateQrErrors];

export type PostApiV1OrderByOrderIdGenerateQrResponses = {
    /**
     * QR pickup berhasil dibuat
     */
    200: GenerateQrResponse;
};

export type PostApiV1OrderByOrderIdGenerateQrResponse = PostApiV1OrderByOrderIdGenerateQrResponses[keyof PostApiV1OrderByOrderIdGenerateQrResponses];

export type GetApiV1PaymentFeeData = {
    body?: never;
    path?: never;
    query: {
        method: string;
        amount: number;
    };
    url: '/api/v1/payment/fee';
};

export type GetApiV1PaymentFeeErrors = {
    /**
     * Validasi gagal (amount tidak valid)
     */
    400: ErrorResponse;
    /**
     * Metode pembayaran tidak tersedia
     */
    404: ErrorResponse;
};

export type GetApiV1PaymentFeeError = GetApiV1PaymentFeeErrors[keyof GetApiV1PaymentFeeErrors];

export type GetApiV1PaymentFeeResponses = {
    /**
     * Perhitungan fee berhasil
     */
    200: PaymentFeeResponse;
};

export type GetApiV1PaymentFeeResponse = GetApiV1PaymentFeeResponses[keyof GetApiV1PaymentFeeResponses];

export type PostApiV1PaymentWebhookNotificationData = {
    body: PaymentWebhookBody;
    path?: never;
    query?: never;
    url: '/api/v1/payment/webhook/notification';
};

export type PostApiV1PaymentWebhookNotificationErrors = {
    /**
     * Signature tidak valid
     */
    401: ErrorResponse;
};

export type PostApiV1PaymentWebhookNotificationError = PostApiV1PaymentWebhookNotificationErrors[keyof PostApiV1PaymentWebhookNotificationErrors];

export type PostApiV1PaymentWebhookNotificationResponses = {
    /**
     * Webhook diterima
     */
    200: PaymentWebhookResponse;
};

export type PostApiV1PaymentWebhookNotificationResponse = PostApiV1PaymentWebhookNotificationResponses[keyof PostApiV1PaymentWebhookNotificationResponses];

export type GetApiV1PaymentMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/payment/methods';
};

export type GetApiV1PaymentMethodsErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
};

export type GetApiV1PaymentMethodsError = GetApiV1PaymentMethodsErrors[keyof GetApiV1PaymentMethodsErrors];

export type GetApiV1PaymentMethodsResponses = {
    /**
     * Metode pembayaran berhasil diambil
     */
    200: PaymentMethodsResponse;
};

export type GetApiV1PaymentMethodsResponse = GetApiV1PaymentMethodsResponses[keyof GetApiV1PaymentMethodsResponses];

export type PostApiV1PaymentByOrderIdInitiateData = {
    body: InitiatePaymentBody;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/payment/{orderId}/initiate';
};

export type PostApiV1PaymentByOrderIdInitiateErrors = {
    /**
     * Validasi gagal
     */
    400: ErrorResponse;
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Order bukan milik user
     */
    403: ErrorResponse;
    /**
     * Order atau metode pembayaran tidak ditemukan
     */
    404: ErrorResponse;
    /**
     * Order sudah dibayar atau sudah expired
     */
    409: ErrorResponse;
    /**
     * Gagal membuat transaksi di payment gateway
     */
    500: ErrorResponse;
};

export type PostApiV1PaymentByOrderIdInitiateError = PostApiV1PaymentByOrderIdInitiateErrors[keyof PostApiV1PaymentByOrderIdInitiateErrors];

export type PostApiV1PaymentByOrderIdInitiateResponses = {
    /**
     * Pembayaran berhasil diinisiasi
     */
    201: InitiatePaymentResponse;
};

export type PostApiV1PaymentByOrderIdInitiateResponse = PostApiV1PaymentByOrderIdInitiateResponses[keyof PostApiV1PaymentByOrderIdInitiateResponses];

export type GetApiV1PaymentByOrderIdStatusData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/payment/{orderId}/status';
};

export type GetApiV1PaymentByOrderIdStatusErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Order bukan milik user
     */
    403: ErrorResponse;
    /**
     * Order tidak ditemukan
     */
    404: ErrorResponse;
    /**
     * Order belum dikonfirmasi untuk pembayaran
     */
    409: ErrorResponse;
    /**
     * Terlalu banyak polling status pembayaran untuk order ini
     */
    429: ErrorResponse;
};

export type GetApiV1PaymentByOrderIdStatusError = GetApiV1PaymentByOrderIdStatusErrors[keyof GetApiV1PaymentByOrderIdStatusErrors];

export type GetApiV1PaymentByOrderIdStatusResponses = {
    /**
     * Status pembayaran
     */
    200: PaymentStatusResponse;
};

export type GetApiV1PaymentByOrderIdStatusResponse = GetApiV1PaymentByOrderIdStatusResponses[keyof GetApiV1PaymentByOrderIdStatusResponses];

export type GetApiV1PaymentByOrderIdData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/payment/{orderId}';
};

export type GetApiV1PaymentByOrderIdErrors = {
    /**
     * Tidak terautentikasi
     */
    401: ErrorResponse;
    /**
     * Pembayaran bukan milik user
     */
    403: ErrorResponse;
    /**
     * Pembayaran tidak ditemukan
     */
    404: ErrorResponse;
};

export type GetApiV1PaymentByOrderIdError = GetApiV1PaymentByOrderIdErrors[keyof GetApiV1PaymentByOrderIdErrors];

export type GetApiV1PaymentByOrderIdResponses = {
    /**
     * Detail pembayaran
     */
    200: PaymentDetailResponse;
};

export type GetApiV1PaymentByOrderIdResponse = GetApiV1PaymentByOrderIdResponses[keyof GetApiV1PaymentByOrderIdResponses];

export type GetApiV1AdminProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Nomor halaman, minimal 1 dan tidak boleh melebihi halaman terakhir (default: 1)
         */
        page?: number;
        /**
         * Jumlah item per halaman, minimal 1 dan maksimal 100 (default: 20)
         */
        limit?: number;
        search?: string;
        /**
         * Filter berdasarkan tipe produk
         */
        type?: 'merchandise' | 'collaboration' | 'kit_panitia';
        category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle';
        /**
         * Filter berdasarkan fakultas (untuk produk collaboration). Bisa repeated query (?faculty=STEI&faculty=FTSL) atau comma-separated (?faculty=STEI,FTSL).
         */
        faculty?: Array<string> | null;
        /**
         * Field untuk pengurutan (default: createdAt)
         */
        sortBy?: 'name' | 'totalSold' | 'totalRevenue' | 'createdAt';
        /**
         * Urutan pengurutan (default: desc)
         */
        sortOrder?: 'asc' | 'desc';
    };
    url: '/api/v1/admin/products';
};

export type GetApiV1AdminProductsErrors = {
    /**
     * Query parameter tidak sesuai dengan batas atau format yang ditentukan
     */
    400: ErrorResponse;
    /**
     * Input tidak valid
     */
    401: ErrorResponse;
    /**
     * Input tidak valid
     */
    403: ErrorResponse;
};

export type GetApiV1AdminProductsError = GetApiV1AdminProductsErrors[keyof GetApiV1AdminProductsErrors];

export type GetApiV1AdminProductsResponses = {
    /**
     * Daftar produk beserta statistik penjualan berhasil diambil
     */
    200: AdminProductListResponse;
};

export type GetApiV1AdminProductsResponse = GetApiV1AdminProductsResponses[keyof GetApiV1AdminProductsResponses];

export type GetApiV1AdminDashboardItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Nomor halaman, minimal 1 dan tidak boleh melebihi halaman terakhir (default: 1)
         */
        page?: number;
        /**
         * Jumlah item per halaman, minimal 1 dan maksimal 100 (default: 20)
         */
        limit?: number;
        search?: string;
        /**
         * Filter berdasarkan tipe produk
         */
        type?: 'merchandise' | 'collaboration' | 'kit_panitia';
        category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle';
        /**
         * Filter berdasarkan fakultas (untuk produk collaboration). Bisa repeated query (?faculty=STEI&faculty=FTSL) atau comma-separated (?faculty=STEI,FTSL).
         */
        faculty?: Array<string> | null;
        /**
         * Field untuk pengurutan (default: createdAt)
         */
        sortBy?: 'name' | 'totalSold' | 'totalRevenue' | 'createdAt';
        /**
         * Urutan pengurutan (default: desc)
         */
        sortOrder?: 'asc' | 'desc';
    };
    url: '/api/v1/admin/dashboard/items';
};

export type GetApiV1AdminDashboardItemsErrors = {
    /**
     * Query parameter tidak sesuai dengan batas atau format yang ditentukan
     */
    400: ErrorResponse;
    /**
     * Input tidak valid
     */
    401: ErrorResponse;
    /**
     * Input tidak valid
     */
    403: ErrorResponse;
};

export type GetApiV1AdminDashboardItemsError = GetApiV1AdminDashboardItemsErrors[keyof GetApiV1AdminDashboardItemsErrors];

export type GetApiV1AdminDashboardItemsResponses = {
    /**
     * Daftar item dashboard (produk + statistik penjualan) berhasil diambil
     */
    200: AdminProductListResponse;
};

export type GetApiV1AdminDashboardItemsResponse = GetApiV1AdminDashboardItemsResponses[keyof GetApiV1AdminDashboardItemsResponses];

export type GetApiV1AdminProductsCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter berdasarkan kategori. Jika tidak diisi, mengembalikan semua kategori.
         */
        category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris' | 'bundle';
        /**
         * Nomor halaman, minimal 1 dan tidak boleh melebihi halaman terakhir (default: 1)
         */
        page?: number;
        /**
         * Jumlah item per halaman, minimal 1 dan maksimal 100 (default: 20)
         */
        limit?: number;
        search?: string;
    };
    url: '/api/v1/admin/products/categories';
};

export type GetApiV1AdminProductsCategoriesErrors = {
    /**
     * Query parameter tidak sesuai dengan batas atau format yang ditentukan
     */
    400: ErrorResponse;
    /**
     * Input tidak valid
     */
    401: ErrorResponse;
    /**
     * Input tidak valid
     */
    403: ErrorResponse;
};

export type GetApiV1AdminProductsCategoriesError = GetApiV1AdminProductsCategoriesErrors[keyof GetApiV1AdminProductsCategoriesErrors];

export type GetApiV1AdminProductsCategoriesResponses = {
    /**
     * Produk per kategori beserta statistik penjualan berhasil diambil
     */
    200: AdminProductListResponse;
};

export type GetApiV1AdminProductsCategoriesResponse = GetApiV1AdminProductsCategoriesResponses[keyof GetApiV1AdminProductsCategoriesResponses];

export type GetApiV1AdminDashboardTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Nomor halaman, minimal 1 dan tidak boleh melebihi halaman terakhir (default: 1)
         */
        page?: number;
        /**
         * Jumlah transaksi per halaman, minimal 1 dan maksimal 100 (default: 10)
         */
        limit?: number;
        /**
         * Cari nama/email/phone/LINE ID pembeli atau nama produk pada transaksi
         */
        search?: string;
        /**
         * Filter status order. Bisa repeated query (?status=lunas&status=diterima) atau comma-separated (?status=lunas,diterima).
         */
        status?: Array<'belum_bayar' | 'lunas' | 'diterima' | 'expired'>;
        /**
         * Batas awal inclusive untuk created_at atau paid_at transaksi
         */
        date_from?: string;
        /**
         * Batas akhir inclusive untuk created_at atau paid_at transaksi
         */
        date_to?: string;
        /**
         * Field pengurutan transaksi (default: created_at)
         */
        sort_by?: 'created_at' | 'paid_at';
        /**
         * Urutan pengurutan transaksi (default: desc)
         */
        sort_order?: 'asc' | 'desc';
    };
    url: '/api/v1/admin/dashboard/transactions';
};

export type GetApiV1AdminDashboardTransactionsErrors = {
    /**
     * Query parameter tidak sesuai dengan batas atau format yang ditentukan
     */
    400: ErrorResponse;
    /**
     * Input tidak valid
     */
    401: ErrorResponse;
    /**
     * Input tidak valid
     */
    403: ErrorResponse;
};

export type GetApiV1AdminDashboardTransactionsError = GetApiV1AdminDashboardTransactionsErrors[keyof GetApiV1AdminDashboardTransactionsErrors];

export type GetApiV1AdminDashboardTransactionsResponses = {
    /**
     * Daftar transaksi dashboard admin berhasil diambil
     */
    200: AdminTransactionListResponse;
};

export type GetApiV1AdminDashboardTransactionsResponse = GetApiV1AdminDashboardTransactionsResponses[keyof GetApiV1AdminDashboardTransactionsResponses];

export type PostApiV1AdminHandOverScanData = {
    body: AdminHandOverScanBody;
    path?: never;
    query?: never;
    url: '/api/v1/admin/hand-over/scan';
};

export type PostApiV1AdminHandOverScanErrors = {
    /**
     * QR sudah expired, sudah digunakan, tidak valid, atau order belum lunas
     */
    400: ErrorResponse;
    /**
     * Input tidak valid
     */
    401: ErrorResponse;
    /**
     * Input tidak valid
     */
    403: ErrorResponse;
    /**
     * QR pickup tidak ditemukan
     */
    404: ErrorResponse;
};

export type PostApiV1AdminHandOverScanError = PostApiV1AdminHandOverScanErrors[keyof PostApiV1AdminHandOverScanErrors];

export type PostApiV1AdminHandOverScanResponses = {
    /**
     * QR pickup valid dan detail transaksi berhasil diambil
     */
    200: AdminHandOverScanResponse;
};

export type PostApiV1AdminHandOverScanResponse = PostApiV1AdminHandOverScanResponses[keyof PostApiV1AdminHandOverScanResponses];

export type PatchApiV1AdminHandOverConfirmByTransactionIdData = {
    body?: never;
    path: {
        /**
         * ID transaksi/order yang akan dikonfirmasi hand-over
         */
        transactionId: string;
    };
    query?: never;
    url: '/api/v1/admin/hand-over/confirm/{transactionId}';
};

export type PatchApiV1AdminHandOverConfirmByTransactionIdErrors = {
    /**
     * Order belum lunas, sudah expired, atau sudah diterima
     */
    400: ErrorResponse;
    /**
     * Input tidak valid
     */
    401: ErrorResponse;
    /**
     * Input tidak valid
     */
    403: ErrorResponse;
    /**
     * Order tidak ditemukan
     */
    404: ErrorResponse;
};

export type PatchApiV1AdminHandOverConfirmByTransactionIdError = PatchApiV1AdminHandOverConfirmByTransactionIdErrors[keyof PatchApiV1AdminHandOverConfirmByTransactionIdErrors];

export type PatchApiV1AdminHandOverConfirmByTransactionIdResponses = {
    /**
     * Serah terima berhasil dikonfirmasi
     */
    200: AdminHandOverConfirmResponse;
};

export type PatchApiV1AdminHandOverConfirmByTransactionIdResponse = PatchApiV1AdminHandOverConfirmByTransactionIdResponses[keyof PatchApiV1AdminHandOverConfirmByTransactionIdResponses];

export type GetApiV1HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetApiV1HealthResponses = {
    /**
     * Server berjalan normal
     */
    200: {
        status: 'ok';
        timestamp: string;
        uptime: number;
        environment: string;
    };
};

export type GetApiV1HealthResponse = GetApiV1HealthResponses[keyof GetApiV1HealthResponses];

// ---------------------------------------------------------------------------
// Admin additions (transaction detail + items summary + faculty filter).
// Kept in sync with backend admin.schema.ts. Regenerate via openapi:generate
// once the backend changes are deployed to the live OpenAPI.
// ---------------------------------------------------------------------------

export type AdminItemsSummaryResponse = {
    success: true;
    data: {
        totalProduk: number;
        totalItemTerjual: number;
        totalPendapatan: number;
    };
};

export type AdminOrderDetailItem = {
    productName: string;
    variantSnapshot: {
        [key: string]: unknown;
    };
    quantity: number;
    unitPrice: number;
    subtotal: number;
};

export type AdminOrderDetailResponse = {
    success: true;
    data: {
        orderId: string;
        buyerName: string;
        buyerEmail: string;
        buyerPhone: string | null;
        buyerLineId: string | null;
        deliveryMethod: 'pickup' | 'shipping' | null;
        deliveryAddress: string | null;
        paymentMethod: string | null;
        items: Array<AdminOrderDetailItem>;
        subtotal: number;
        fee: number;
        totalBilled: number;
        status: 'belum_bayar' | 'lunas' | 'diterima' | 'expired';
        paidAt: string | null;
        createdAt: string;
    };
};

export type GetApiV1AdminDashboardItemsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/dashboard/items/summary';
};

export type GetApiV1AdminDashboardItemsSummaryErrors = {
    401: ErrorResponse;
    403: ErrorResponse;
};

export type GetApiV1AdminDashboardItemsSummaryError = GetApiV1AdminDashboardItemsSummaryErrors[keyof GetApiV1AdminDashboardItemsSummaryErrors];

export type GetApiV1AdminDashboardItemsSummaryResponses = {
    200: AdminItemsSummaryResponse;
};

export type GetApiV1AdminDashboardItemsSummaryResponse = GetApiV1AdminDashboardItemsSummaryResponses[keyof GetApiV1AdminDashboardItemsSummaryResponses];

export type GetApiV1AdminDashboardTransactionsByOrderIdData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/admin/dashboard/transactions/{orderId}';
};

export type GetApiV1AdminDashboardTransactionsByOrderIdErrors = {
    401: ErrorResponse;
    403: ErrorResponse;
    404: ErrorResponse;
};

export type GetApiV1AdminDashboardTransactionsByOrderIdError = GetApiV1AdminDashboardTransactionsByOrderIdErrors[keyof GetApiV1AdminDashboardTransactionsByOrderIdErrors];

export type GetApiV1AdminDashboardTransactionsByOrderIdResponses = {
    200: AdminOrderDetailResponse;
};

export type GetApiV1AdminDashboardTransactionsByOrderIdResponse = GetApiV1AdminDashboardTransactionsByOrderIdResponses[keyof GetApiV1AdminDashboardTransactionsByOrderIdResponses];
