// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5002' | (string & {});
};

export type SignupResponse = {
  success: true;
  data: {
    message: string;
    email: string;
  };
};

export type ErrorResponse = {
  success: false;
  error: {
    code: string;
    message: string;
  };
};

export type SignupBody = {
  name: string;
  email: string;
  /**
   * Min 8 karakter, mengandung huruf besar, huruf kecil, dan angka
   */
  password: string;
};

export type LoginResponse = {
  success: true;
  data: {
    accessToken: string;
    user: AuthUser;
  };
};

export type AuthUser = {
  id: string;
  name: string;
  email: string;
  role: 'umum' | 'panitia' | 'admin';
  isOnboardingComplete: boolean;
};

export type LoginBody = {
  email: string;
  password: string;
};

export type VerifyOtpResponse = {
  success: true;
  data: {
    /**
     * Token sementara untuk proses onboarding. Gunakan sebagai Bearer token di endpoint POST /auth/onboarding. Berlaku 30 menit.
     */
    onboardingToken: string;
    message: string;
  };
};

export type VerifyOtpBody = {
  email: string;
  otp: string;
};

export type ResendOtpResponse = {
  success: true;
  data: {
    message: string;
  };
};

export type ResendOtpBody = {
  email: string;
};

export type RefreshTokenResponse = {
  success: true;
  data: {
    accessToken: string;
  };
};

export type LogoutResponse = {
  success: true;
  data: {
    message: string;
  };
};

export type ChangePasswordResponse = {
  success: true;
  data: {
    message: string;
  };
};

export type ChangePasswordBody = {
  oldPassword: string;
  /**
   * Min 8 karakter, mengandung huruf besar, huruf kecil, dan angka
   */
  newPassword: string;
  /**
   * Harus sama dengan newPassword
   */
  confirmPassword: string;
};

export type OnboardingResponse = {
  success: true;
  data: {
    accessToken: string;
    user: AuthUser;
  };
};

export type OnboardingBody = {
  /**
   * ID LINE akun pengguna
   */
  lineId: string;
  phone: string;
  /**
   * Tipe pengguna yang dipilih saat onboarding
   */
  role: 'umum' | 'panitia';
  /**
   * NIM mahasiswa. WAJIB diisi jika role = panitia.
   */
  nim?: string;
  /**
   * Kode bidang panitia. WAJIB diisi jika role = panitia. Harus valid sesuai database panitia_divisions.
   */
  divisionCode?: string;
};

export type UserProfileResponse = {
  success: true;
  data: UserProfile;
};

export type UserProfile = {
  id: string;
  name: string;
  email: string;
  role: 'umum' | 'panitia' | 'admin';
  lineId: string;
  phone: string;
  /**
   * Khusus panitia
   */
  nim: string;
  division: Division;
  /**
   * Nomor kelompok MaBa. Opsional untuk umum.
   */
  kelompok: string;
};

/**
 * Bidang panitia. Null jika bukan panitia.
 */
export type Division = {
  id: string;
  name: string;
  code: string;
};

export type PatchProfileResponse = {
  success: true;
  data: UserProfile;
};

export type PatchProfileBody = {
  name?: string;
  lineId?: string;
  phone?: string;
};

export type IsAdminResponse = {
  success: true;
  data: {
    isAdmin: boolean;
  };
};

export type ProductListResponse = {
  success: true;
  data: Array<ProductListItem>;
  meta: PaginationMeta;
};

export type ProductListItem = {
  id: string;
  name: string;
  description: string;
  /**
   * Harga dasar produk dalam IDR
   */
  basePrice: number;
  type: 'merchandise' | 'collaboration' | 'kit_panitia';
  category: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
  /**
   * Nama fakultas, hanya untuk produk collaboration
   */
  faculty: string;
  primaryImage: ProductImage;
  /**
   * Jumlah varian yang tersedia
   */
  variantCount: number;
  /**
   * Harga terendah dari semua varian
   */
  minPrice: number;
  /**
   * Harga tertinggi dari semua varian
   */
  maxPrice: number;
};

/**
 * Gambar utama produk (is_primary = true)
 */
export type ProductImage = {
  id: string;
  url: string;
  isPrimary: boolean;
  sortOrder: number;
};

export type PaginationMeta = {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
};

export type ProductDetailResponse = {
  success: true;
  data: ProductDetail;
};

export type ProductDetail = {
  id: string;
  name: string;
  description: string;
  basePrice: number;
  type: 'merchandise' | 'collaboration' | 'kit_panitia';
  category: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
  faculty: string;
  /**
   * Semua gambar produk, diurutkan berdasarkan sort_order
   */
  images: Array<ProductImage>;
  /**
   * Semua varian produk yang tersedia
   */
  variants: Array<ProductVariant>;
};

export type ProductVariant = {
  id: string;
  sleeveType: 'lengan_panjang' | 'lengan_pendek' | 'none';
  color: string;
  size: 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'none';
  /**
   * Harga tambahan di atas base_price produk (dalam IDR, bisa 0 atau positif)
   */
  priceModifier: number;
  stock: number;
  sku: string;
  /**
   * Harga akhir = base_price + price_modifier
   */
  finalPrice: number;
};

export type AdminProductListResponse = {
  success: true;
  data: Array<AdminProduct>;
  meta: PaginationMeta;
};

export type AdminProduct = {
  id: string;
  name: string;
  description: string;
  basePrice: number;
  type: 'merchandise' | 'collaboration' | 'kit_panitia';
  category: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
  faculty: string;
  isActive: boolean;
  primaryImage: ProductImage;
  salesStats: ProductSalesStats;
};

export type ProductSalesStats = {
  /**
   * Total unit terjual dari semua varian produk ini
   */
  totalSold: number;
  /**
   * Total pendapatan produk ini dari semua transaksi lunas (IDR)
   */
  totalRevenue: number;
  /**
   * Rincian penjualan per varian
   */
  variantStats: Array<VariantSalesStats>;
};

export type VariantSalesStats = {
  variantId: string;
  sleeveType: 'lengan_panjang' | 'lengan_pendek' | 'none';
  color: string;
  size: 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'none';
  sku: string;
  /**
   * Harga per unit saat terjual
   */
  unitPrice: number;
  /**
   * Total unit terjual dari varian ini
   */
  totalSold: number;
  /**
   * Total pendapatan dari varian ini (IDR)
   */
  totalRevenue: number;
};

export type PostApiV1AuthSignupData = {
  body: SignupBody;
  path?: never;
  query?: never;
  url: '/api/v1/auth/signup';
};

export type PostApiV1AuthSignupErrors = {
  /**
   * Validasi gagal (password lemah, format email salah, dll.)
   */
  400: ErrorResponse;
  /**
   * Email sudah terdaftar
   */
  409: ErrorResponse;
  /**
   * Terlalu banyak permintaan — rate limit terlampaui (maks 3x/jam/IP)
   */
  429: ErrorResponse;
};

export type PostApiV1AuthSignupError = PostApiV1AuthSignupErrors[keyof PostApiV1AuthSignupErrors];

export type PostApiV1AuthSignupResponses = {
  /**
   * Registrasi berhasil, OTP dikirim ke email
   */
  201: SignupResponse;
};

export type PostApiV1AuthSignupResponse =
  PostApiV1AuthSignupResponses[keyof PostApiV1AuthSignupResponses];

export type PostApiV1AuthLoginData = {
  body: LoginBody;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
  /**
   * Validasi gagal (field kosong, format email salah)
   */
  400: ErrorResponse;
  /**
   * Email atau password salah
   */
  401: ErrorResponse;
  /**
   * Terlalu banyak percobaan login — rate limit terlampaui (maks 5x/15 menit)
   */
  429: ErrorResponse;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
  /**
   * Login berhasil. Refresh token diset sebagai HTTP-only cookie `refresh_token`.
   */
  200: LoginResponse;
};

export type PostApiV1AuthLoginResponse =
  PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthVerifyOtpData = {
  body: VerifyOtpBody;
  path?: never;
  query?: never;
  url: '/api/v1/auth/verify-otp';
};

export type PostApiV1AuthVerifyOtpErrors = {
  /**
   * Format OTP tidak valid atau OTP salah
   */
  400: ErrorResponse;
  /**
   * OTP kedaluwarsa atau sudah digunakan
   */
  401: ErrorResponse;
  /**
   * Email tidak ditemukan atau tidak sedang menunggu verifikasi
   */
  404: ErrorResponse;
};

export type PostApiV1AuthVerifyOtpError =
  PostApiV1AuthVerifyOtpErrors[keyof PostApiV1AuthVerifyOtpErrors];

export type PostApiV1AuthVerifyOtpResponses = {
  /**
   * OTP valid, onboardingToken dikembalikan
   */
  200: VerifyOtpResponse;
};

export type PostApiV1AuthVerifyOtpResponse =
  PostApiV1AuthVerifyOtpResponses[keyof PostApiV1AuthVerifyOtpResponses];

export type PostApiV1AuthResendOtpData = {
  body: ResendOtpBody;
  path?: never;
  query?: never;
  url: '/api/v1/auth/resend-otp';
};

export type PostApiV1AuthResendOtpErrors = {
  /**
   * Validasi gagal (format email salah)
   */
  400: ErrorResponse;
  /**
   * Email tidak ditemukan atau akun sudah terverifikasi
   */
  404: ErrorResponse;
  /**
   * Terlalu banyak permintaan — rate limit terlampaui (maks 3x/jam/IP)
   */
  429: ErrorResponse;
};

export type PostApiV1AuthResendOtpError =
  PostApiV1AuthResendOtpErrors[keyof PostApiV1AuthResendOtpErrors];

export type PostApiV1AuthResendOtpResponses = {
  /**
   * OTP baru berhasil dikirim
   */
  200: ResendOtpResponse;
};

export type PostApiV1AuthResendOtpResponse =
  PostApiV1AuthResendOtpResponses[keyof PostApiV1AuthResendOtpResponses];

export type PostApiV1AuthRefreshTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/refresh-token';
};

export type PostApiV1AuthRefreshTokenErrors = {
  /**
   * Refresh token tidak valid, kedaluwarsa, atau tidak ada cookie
   */
  401: ErrorResponse;
};

export type PostApiV1AuthRefreshTokenError =
  PostApiV1AuthRefreshTokenErrors[keyof PostApiV1AuthRefreshTokenErrors];

export type PostApiV1AuthRefreshTokenResponses = {
  /**
   * Access token baru berhasil dibuat. Refresh token baru diset sebagai HTTP-only cookie.
   */
  200: RefreshTokenResponse;
};

export type PostApiV1AuthRefreshTokenResponse =
  PostApiV1AuthRefreshTokenResponses[keyof PostApiV1AuthRefreshTokenResponses];

export type PostApiV1AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
  /**
   * Logout berhasil, cookie refresh_token dihapus
   */
  200: LogoutResponse;
};

export type PostApiV1AuthLogoutResponse =
  PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type PostApiV1AuthChangePasswordData = {
  body: ChangePasswordBody;
  path?: never;
  query?: never;
  url: '/api/v1/auth/change-password';
};

export type PostApiV1AuthChangePasswordErrors = {
  /**
   * Validasi gagal (password baru lemah, confirmPassword tidak cocok, dll.)
   */
  400: ErrorResponse;
  /**
   * Tidak terautentikasi atau password lama salah
   */
  401: ErrorResponse;
};

export type PostApiV1AuthChangePasswordError =
  PostApiV1AuthChangePasswordErrors[keyof PostApiV1AuthChangePasswordErrors];

export type PostApiV1AuthChangePasswordResponses = {
  /**
   * Password berhasil diubah, semua sesi lain dinonaktifkan
   */
  200: ChangePasswordResponse;
};

export type PostApiV1AuthChangePasswordResponse =
  PostApiV1AuthChangePasswordResponses[keyof PostApiV1AuthChangePasswordResponses];

export type PostApiV1AuthOnboardingData = {
  body: OnboardingBody;
  path?: never;
  query?: never;
  url: '/api/v1/auth/onboarding';
};

export type PostApiV1AuthOnboardingErrors = {
  /**
   * Validasi gagal — untuk panitia: kode bidang tidak valid, NIM kosong, dll.
   */
  400: ErrorResponse;
  /**
   * Onboarding token tidak valid atau kedaluwarsa
   */
  401: ErrorResponse;
  /**
   * Onboarding sudah diselesaikan sebelumnya
   */
  409: ErrorResponse;
};

export type PostApiV1AuthOnboardingError =
  PostApiV1AuthOnboardingErrors[keyof PostApiV1AuthOnboardingErrors];

export type PostApiV1AuthOnboardingResponses = {
  /**
   * Onboarding berhasil. Access token dikembalikan, refresh token diset sebagai cookie.
   */
  200: OnboardingResponse;
};

export type PostApiV1AuthOnboardingResponse =
  PostApiV1AuthOnboardingResponses[keyof PostApiV1AuthOnboardingResponses];

export type GetApiV1UserProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/user/profile';
};

export type GetApiV1UserProfileErrors = {
  /**
   * Tidak terautentikasi - access token tidak ada atau kedaluwarsa
   */
  401: ErrorResponse;
};

export type GetApiV1UserProfileError = GetApiV1UserProfileErrors[keyof GetApiV1UserProfileErrors];

export type GetApiV1UserProfileResponses = {
  /**
   * Data profil berhasil diambil
   */
  200: UserProfileResponse;
};

export type GetApiV1UserProfileResponse =
  GetApiV1UserProfileResponses[keyof GetApiV1UserProfileResponses];

export type PatchApiV1UserProfileData = {
  body: PatchProfileBody;
  path?: never;
  query?: never;
  url: '/api/v1/user/profile';
};

export type PatchApiV1UserProfileErrors = {
  /**
   * Validasi gagal (format nomor telepon salah, dll.)
   */
  400: ErrorResponse;
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
};

export type PatchApiV1UserProfileError =
  PatchApiV1UserProfileErrors[keyof PatchApiV1UserProfileErrors];

export type PatchApiV1UserProfileResponses = {
  /**
   * Profil berhasil diperbarui, mengembalikan data profil terbaru
   */
  200: PatchProfileResponse;
};

export type PatchApiV1UserProfileResponse =
  PatchApiV1UserProfileResponses[keyof PatchApiV1UserProfileResponses];

export type GetApiV1UserProfileIsAdminData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/user/profile/is-admin';
};

export type GetApiV1UserProfileIsAdminErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
};

export type GetApiV1UserProfileIsAdminError =
  GetApiV1UserProfileIsAdminErrors[keyof GetApiV1UserProfileIsAdminErrors];

export type GetApiV1UserProfileIsAdminResponses = {
  /**
   * Status admin berhasil diperiksa
   */
  200: IsAdminResponse;
};

export type GetApiV1UserProfileIsAdminResponse =
  GetApiV1UserProfileIsAdminResponses[keyof GetApiV1UserProfileIsAdminResponses];

export type GetApiV1ProductMerchData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Nomor halaman (default: 1)
     */
    page?: string;
    /**
     * Jumlah item per halaman (default: 10, maks: 50)
     */
    limit?: string;
    /**
     * Pencarian teks pada nama produk (case-insensitive)
     */
    search?: string;
    /**
     * Filter berdasarkan kategori
     */
    category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
  };
  url: '/api/v1/product/merch';
};

export type GetApiV1ProductMerchErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
};

export type GetApiV1ProductMerchError =
  GetApiV1ProductMerchErrors[keyof GetApiV1ProductMerchErrors];

export type GetApiV1ProductMerchResponses = {
  /**
   * Daftar produk merchandise berhasil diambil
   */
  200: ProductListResponse;
};

export type GetApiV1ProductMerchResponse =
  GetApiV1ProductMerchResponses[keyof GetApiV1ProductMerchResponses];

export type GetApiV1ProductPanitiaData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Nomor halaman (default: 1)
     */
    page?: string;
    /**
     * Jumlah item per halaman (default: 10, maks: 50)
     */
    limit?: string;
    /**
     * Pencarian teks pada nama produk (case-insensitive)
     */
    search?: string;
    /**
     * Filter berdasarkan kategori
     */
    category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
  };
  url: '/api/v1/product/panitia';
};

export type GetApiV1ProductPanitiaErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
  /**
   * Akses ditolak — hanya untuk panitia dan admin
   */
  403: ErrorResponse;
};

export type GetApiV1ProductPanitiaError =
  GetApiV1ProductPanitiaErrors[keyof GetApiV1ProductPanitiaErrors];

export type GetApiV1ProductPanitiaResponses = {
  /**
   * Daftar produk kit panitia berhasil diambil
   */
  200: ProductListResponse;
};

export type GetApiV1ProductPanitiaResponse =
  GetApiV1ProductPanitiaResponses[keyof GetApiV1ProductPanitiaResponses];

export type GetApiV1ProductCollabData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Nomor halaman (default: 1)
     */
    page?: string;
    /**
     * Jumlah item per halaman (default: 10, maks: 50)
     */
    limit?: string;
    /**
     * Pencarian teks pada nama produk (case-insensitive)
     */
    search?: string;
    /**
     * Filter berdasarkan kategori
     */
    category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
    /**
     * Filter berdasarkan nama fakultas (khusus produk kolaborasi)
     */
    faculty?: string;
  };
  url: '/api/v1/product/collab';
};

export type GetApiV1ProductCollabErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
};

export type GetApiV1ProductCollabError =
  GetApiV1ProductCollabErrors[keyof GetApiV1ProductCollabErrors];

export type GetApiV1ProductCollabResponses = {
  /**
   * Daftar produk kolaborasi berhasil diambil
   */
  200: ProductListResponse;
};

export type GetApiV1ProductCollabResponse =
  GetApiV1ProductCollabResponses[keyof GetApiV1ProductCollabResponses];

export type GetApiV1ProductCategoriesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter kategori. Jika tidak diisi, mengembalikan semua kategori.
     */
    category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
    page?: string;
    limit?: string;
    search?: string;
  };
  url: '/api/v1/product/categories';
};

export type GetApiV1ProductCategoriesErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
};

export type GetApiV1ProductCategoriesError =
  GetApiV1ProductCategoriesErrors[keyof GetApiV1ProductCategoriesErrors];

export type GetApiV1ProductCategoriesResponses = {
  /**
   * Produk berhasil diambil
   */
  200: ProductListResponse;
};

export type GetApiV1ProductCategoriesResponse =
  GetApiV1ProductCategoriesResponses[keyof GetApiV1ProductCategoriesResponses];

export type GetApiV1ProductIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/product/:id';
};

export type GetApiV1ProductIdErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
  /**
   * Akses ditolak — produk kit_panitia tidak dapat diakses oleh umum
   */
  403: ErrorResponse;
  /**
   * Produk tidak ditemukan atau sudah dinonaktifkan
   */
  404: ErrorResponse;
};

export type GetApiV1ProductIdError = GetApiV1ProductIdErrors[keyof GetApiV1ProductIdErrors];

export type GetApiV1ProductIdResponses = {
  /**
   * Detail produk berhasil diambil
   */
  200: ProductDetailResponse;
};

export type GetApiV1ProductIdResponse =
  GetApiV1ProductIdResponses[keyof GetApiV1ProductIdResponses];

export type GetApiV1AdminProductsData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    /**
     * Maks 100 per halaman
     */
    limit?: string;
    search?: string;
    /**
     * Filter berdasarkan tipe produk
     */
    type?: 'merchandise' | 'collaboration' | 'kit_panitia';
    category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
    /**
     * Field untuk pengurutan (default: createdAt)
     */
    sortBy?: 'name' | 'totalSold' | 'totalRevenue' | 'createdAt';
    /**
     * Urutan pengurutan (default: desc)
     */
    sortOrder?: 'asc' | 'desc';
  };
  url: '/api/v1/admin/products';
};

export type GetApiV1AdminProductsErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
  /**
   * Akses ditolak — hanya admin
   */
  403: ErrorResponse;
};

export type GetApiV1AdminProductsError =
  GetApiV1AdminProductsErrors[keyof GetApiV1AdminProductsErrors];

export type GetApiV1AdminProductsResponses = {
  /**
   * Daftar produk beserta statistik penjualan berhasil diambil
   */
  200: AdminProductListResponse;
};

export type GetApiV1AdminProductsResponse =
  GetApiV1AdminProductsResponses[keyof GetApiV1AdminProductsResponses];

export type GetApiV1AdminProductsCategoriesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter berdasarkan kategori. Jika tidak diisi, mengembalikan semua kategori.
     */
    category?: 'perhiasan' | 'baju' | 'peralatan_tulis' | 'aksesoris';
    page?: string;
    limit?: string;
    search?: string;
  };
  url: '/api/v1/admin/products/categories';
};

export type GetApiV1AdminProductsCategoriesErrors = {
  /**
   * Tidak terautentikasi
   */
  401: ErrorResponse;
  /**
   * Akses ditolak — hanya admin
   */
  403: ErrorResponse;
};

export type GetApiV1AdminProductsCategoriesError =
  GetApiV1AdminProductsCategoriesErrors[keyof GetApiV1AdminProductsCategoriesErrors];

export type GetApiV1AdminProductsCategoriesResponses = {
  /**
   * Produk per kategori beserta statistik penjualan berhasil diambil
   */
  200: AdminProductListResponse;
};

export type GetApiV1AdminProductsCategoriesResponse =
  GetApiV1AdminProductsCategoriesResponses[keyof GetApiV1AdminProductsCategoriesResponses];

export type GetApiV1HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/health';
};

export type GetApiV1HealthResponses = {
  /**
   * Server berjalan normal
   */
  200: {
    status: 'ok';
    timestamp: string;
    uptime: number;
    environment: string;
  };
};

export type GetApiV1HealthResponse = GetApiV1HealthResponses[keyof GetApiV1HealthResponses];
